Logo
AOT-Technologies/forms-flow-ai-stylesheet pull request #11
Opened 2022-10-28 06:48 UTC by auslin-aot

# Issue Tracking

JIRA: 
Issue Type: FEATURE
https://aottech.atlassian.net/browse/FWF-1791

# Changes
Added Logo styles to design system

# Screenshots
![image](https://user-images.githubusercontent.com/99173163/198520911-ed087af9-c997-473a-9abd-a7ea26f45625.png)

2022-10-28 07:19 UTC, sreehari-aot requested changes

2022-10-28 07:19 UTC, sreehari-aot commented on src/stories/Introduction.stories.mdx
> +<div className="subheading">Image Logo Usage</div>
USAGE only

2022-10-28 07:19 UTC, sreehari-aot commented on src/stories/Introduction.stories.mdx
> +<div className="subheading">Image and Text Logo Usage</div>
only USAGE is needed, if its image only the component should be displayed in such a manner
eg: if its image and logo display image and logo and specify the usage

2022-10-28 07:19 UTC, sreehari-aot commented on src/css/style.css
> +  color: black; }
use variables

2022-10-28 07:19 UTC, sreehari-aot commented on src/css/style.css
> +  font-weight: 700;
define variables for font-weight for logo and use gere

2022-10-28 07:19 UTC, sreehari-aot commented on src/css/components/_logo.scss
> +        color: black;
same use variable for colour

2022-10-31 05:52 UTC, auslin-aot commented on src/stories/Introduction.stories.mdx
> +<div className="subheading">Image Logo Usage</div>
done

2022-10-31 05:52 UTC, auslin-aot commented on src/stories/Introduction.stories.mdx
> +<div className="subheading">Image and Text Logo Usage</div>
done

2022-10-31 05:53 UTC, auslin-aot commented on src/css/components/_logo.scss
> +        color: black;
Added variables.

2022-10-31 12:38 UTC, sreehari-aot approved these changes
Looks good to me

2022-11-03 09:31 UTC, shuhaib-aot requested changes

2022-11-03 09:31 UTC, shuhaib-aot commented on src/css/components/_logo.scss
> +    opacity: 1;
opacity no  needed

2022-11-03 09:31 UTC, shuhaib-aot commented on src/css/components/_logo.scss
> +        color: $color-text-black;
need to bring a variable

2022-11-03 09:51 UTC, auslin-aot commented on src/css/components/_logo.scss
> +    opacity: 1;
Done

2022-11-03 09:51 UTC, auslin-aot commented on src/css/components/_logo.scss
> +        color: $color-text-black;
Done

2022-11-03 12:14 UTC, sreehari-aot approved these changes
Looks good to me

2022-11-04 09:21 UTC, shuhaib-aot approved these changes

2022-11-04 09:34 UTC, shuhaib-aot requested changes
need to bring the text within anchor tag because we need to click in that also

2022-11-08 04:24 UTC, shuhaib-aot approved these changes

2022-11-08 04:24 UTC, shuhaib-aot approved these changes
looks good to me

2022-11-08 04:25 UTC, merged