🎨 Added button tabs and steps
AOT-Technologies/forms-flow-ai-stylesheet pull request #13
Opened 2022-10-28 18:26 UTC by sreehari-aot

2022-11-02 08:13 UTC, shuhaib-aot requested changes

2022-11-02 08:13 UTC, shuhaib-aot commented on src/css/components/_tabs.scss
> +.formsflow-tab button:focus-visible:not(:active) {
user can add class active to active particular  tab

2022-11-02 08:13 UTC, shuhaib-aot commented on src/css/components/_tabs.scss
> +.formsflow-tab-steps button {
please add cursor pointer

2022-11-02 08:13 UTC, shuhaib-aot commented on src/css/components/_tabs.scss
> +.formsflow-tab-steps button {
need to an active class other wise when we click outside the focus will go out so we can't find which tab is active

2022-11-02 08:13 UTC, shuhaib-aot commented on src/css/components/_tabs.scss
> +  width: 20.063rem;
fixed width?

2022-11-02 08:13 UTC, shuhaib-aot commented on src/css/components/_tabs.scss
> +.formsflow-tab-steps button p{
don't use p tab inside the button

2022-11-02 08:13 UTC, shuhaib-aot commented on src/css/components/_tabs.scss
> +.formsflow-tab-steps button p{
please avoid using div inside the p tag . because the p tag and div both are block elements and you can use the p tag directly wrapping inside a div

2022-11-03 08:03 UTC, sreehari-aot commented on src/css/components/_tabs.scss
> +.formsflow-tab button:focus-visible:not(:active) {
active class added

2022-11-03 08:04 UTC, sreehari-aot commented on src/css/components/_tabs.scss
> +.formsflow-tab-steps button {
done

2022-11-03 08:08 UTC, sreehari-aot commented on src/css/components/_tabs.scss
> +.formsflow-tab-steps button {
since it's not clickable, we don't have to make it 👆 right? @shuhaib-aot

2022-11-04 06:03 UTC, shuhaib-aot approved these changes

2022-11-04 06:04 UTC, merged