Progress bar styling
AOT-Technologies/forms-flow-ai-stylesheet pull request #15
Opened 2022-11-02 09:54 UTC by abilpraju-aot

https://aottech.atlassian.net/browse/FWF-1795
![image](https://user-images.githubusercontent.com/83952803/199459342-41056d65-189f-4fb8-ae47-69753d4ec900.png)
![image](https://user-images.githubusercontent.com/83952803/199459395-f7e555ed-d5c0-4d9f-8479-d0bb2e1ef2df.png)

2022-11-03 08:19 UTC, sreehari-aot commented on src/stories/Introduction.stories.mdx
> +       <div class="" style={{"width":"90%"}}></div>
remove empty class

2022-11-03 08:19 UTC, sreehari-aot commented on src/stories/Introduction.stories.mdx
> +    <div class="formsflow-progressbar-container formsflow-progressbar-success" style={{height:"2px"}}>
use correct proper tabbing that might be the reason for parts of the code not getting highlighted in the screenshot

2022-11-03 08:20 UTC, sreehari-aot commented
leave proper spacing between heading, component and code block

2022-11-04 06:08 UTC, shuhaib-aot requested changes
please add description for how to customize progress bar

2022-11-04 17:44 UTC, sreehari-aot commented
please update the screenshots

2022-11-07 15:39 UTC, shuhaib-aot approved these changes

2022-11-07 15:39 UTC, merged